### ISSUE TITLE
HalResources not cleared in ResourceContext

### ISSUE THREAD

**Issue by rivabu** [jcassee/angular-hypermedia#45] opened 2018-01-22 10:28 UTC
Hi,

I'm solving memory issues in our application. One of the issues is the ever growing size of the ResourceContext.

After creating a ResourceContext, and clicking through our application the number of resources is growing rapidly. The number of resources is only increasing and never decreasing.
Is there a way to cleanup unused resources? 

I also tried to put the resources in different ResourceContexts, but that didn't solve my issues either.

In the screenshot, there is 1 ResourceContext with 1216 resources.

<img width="1250" alt="screen shot 2018-01-22 at 11 16" src="https://user-images.githubusercontent.com/1744854/35215990-60006e1e-ff66-11e7-973d-59332b0b8e0c.png">

See the attached screenshot for details.

**Comment by jcassee** [comment] 2018-01-22 12:31
Yes, this is by design and the whole reason d'etre of the `ResourceContext` object: resource scope management. The idea is to scope a context to a "unit of work" that loads a set of related resources. I would advise creating a context in the `resolve` function of the view. (Might be a parent view used by a set of related subviews, of course.)

Does that help?

**Comment by rivabu** [comment] 2018-01-22 13:58
Thanks, but it doesn't solve our issue. 

When we use different ResourceContexts, none of these contexts are cleared. The total number of resources in these contexts isn't lower compared to one ResourceContext.
Do you know why the resources are not removed? I suppose that not-used resources should be  removed from the context automatically?

**Comment by jcassee** [comment] 2018-01-22 14:27
Do you keep references to either the context or its resources? The assumption is that, say, when the user navigates away from a view that had a context defined in its `resolve` function, no other parts of the application keeps references to that context or its resources.

**Comment by rivabu** [comment] 2018-01-23 11:57
Thanks, yes, that's how we did it. But there's still something in our application that has a reference to these resources. We are still searching for the root cause, but the angular-hypermedia modules works as expected.
Thanks for your fast response.

**Comment by jcassee** [comment] 2018-01-23 12:58
Tracking references in JavaScript can be a bit of a pain. :-( I hope you work it out. I'll close this ticket. Feel free to reopen if you discover angular-hypermedia is not doing what it is supposed to do after all.

**Closed as completed by jcassee** 2018-01-23 12:58 UTC
